[build]
builder = "nixpacks"
buildCommand = "npm ci && npm run build"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "npm start"

[[services]]
name = "medusa-backend"

[services.healthcheck]
path = "/health"
port = 9000
intervalSeconds = 10
timeoutSeconds = 5

[services.variables]
PORT = "9000"
NODE_ENV = "production"